baseURL: "https://upbeat-bell-f58be2.netlify.com/"
languageCode: "en-us"
title: "Sean Mahoney"
pygmentsstyle: 'monokai'

# Theme settings
theme: novela
paginate: 6
social:
  twitter: "#"
  github: "https://github.com/seantmahoney92"
  instagram: "https://instagram.com/techno.sheen"
  linkedin: "https://linkedin.com/in/seanmahoney92"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
